#                                                                        #
# Default subroutes configuration for the MicroEvent package             #
#                                                                        #

-
  name: 'Event creation'
  uriPattern:    '{node}/event/create'
  defaults:
    '@package':    'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@format':     'html'
    '@action':     'show'
    '--typo3_neos_nodetypes_typoscript_pluginimplementation':
      '@package':    'Ttree.Plugin.MicroEvent'
      '@controller': 'Event'
      '@action':     'create'
      '@format':     'html'
  routeParts:
    node:
      handler:    TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
  appendExceedingArguments: true